/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApprovalWorkflowService } from "../approvalWorkflow.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalWorkflowCreateInput } from "./ApprovalWorkflowCreateInput";
import { ApprovalWorkflow } from "./ApprovalWorkflow";
import { ApprovalWorkflowFindManyArgs } from "./ApprovalWorkflowFindManyArgs";
import { ApprovalWorkflowWhereUniqueInput } from "./ApprovalWorkflowWhereUniqueInput";
import { ApprovalWorkflowUpdateInput } from "./ApprovalWorkflowUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApprovalWorkflowControllerBase {
  constructor(
    protected readonly service: ApprovalWorkflowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApprovalWorkflow })
  @nestAccessControl.UseRoles({
    resource: "ApprovalWorkflow",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApprovalWorkflow(
    @common.Body() data: ApprovalWorkflowCreateInput
  ): Promise<ApprovalWorkflow> {
    return await this.service.createApprovalWorkflow({
      data: {
        ...data,

        purchaseOrder: data.purchaseOrder
          ? {
              connect: data.purchaseOrder,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        level: true,

        purchaseOrder: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApprovalWorkflow] })
  @ApiNestedQuery(ApprovalWorkflowFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApprovalWorkflow",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async approvalWorkflows(
    @common.Req() request: Request
  ): Promise<ApprovalWorkflow[]> {
    const args = plainToClass(ApprovalWorkflowFindManyArgs, request.query);
    return this.service.approvalWorkflows({
      ...args,
      select: {
        createdAt: true,
        id: true,
        level: true,

        purchaseOrder: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApprovalWorkflow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalWorkflow",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async approvalWorkflow(
    @common.Param() params: ApprovalWorkflowWhereUniqueInput
  ): Promise<ApprovalWorkflow | null> {
    const result = await this.service.approvalWorkflow({
      where: params,
      select: {
        createdAt: true,
        id: true,
        level: true,

        purchaseOrder: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApprovalWorkflow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalWorkflow",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApprovalWorkflow(
    @common.Param() params: ApprovalWorkflowWhereUniqueInput,
    @common.Body() data: ApprovalWorkflowUpdateInput
  ): Promise<ApprovalWorkflow | null> {
    try {
      return await this.service.updateApprovalWorkflow({
        where: params,
        data: {
          ...data,

          purchaseOrder: data.purchaseOrder
            ? {
                connect: data.purchaseOrder,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          level: true,

          purchaseOrder: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApprovalWorkflow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalWorkflow",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApprovalWorkflow(
    @common.Param() params: ApprovalWorkflowWhereUniqueInput
  ): Promise<ApprovalWorkflow | null> {
    try {
      return await this.service.deleteApprovalWorkflow({
        where: params,
        select: {
          createdAt: true,
          id: true,
          level: true,

          purchaseOrder: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
